// Kernel Events module — public barrel
// bus() is the single access point. Nothing calls EventEmitter directly.
export { bus, _resetBus } from './bus.js';
export type { EventBus } from './bus.js';
export { logDomainEvent } from './log.js';
export {
  dispatchMessageReceived,
  dispatchMessageSent,
  dispatchMessageDelivered,
  dispatchMessageRead,
  dispatchMessageFailed,
  dispatchConversationCreated,
  dispatchConversationAssigned,
  dispatchConversationPriorityChanged,
  dispatchConversationStatusChanged,
  dispatchSlaResponseDue,
  dispatchSlaBreached,
  dispatchCustomerCreated,
  dispatchCustomerTagged,
  dispatchCustomerNoted,
  dispatchCampaignStarted,
  dispatchCampaignCompleted,
  dispatchAutomationTriggered,
  dispatchFlowStarted,
  dispatchFlowStep,
  dispatchFlowCompleted,
  dispatchAiReplyGenerated,
  dispatchAiHandoffRequested,
  dispatchAiStateChanged,
  dispatchIntegrationConnected,
  dispatchIntegrationSynced,
  dispatchOrderCreated,
  dispatchOrderFulfilled,
  dispatchInventoryUpdated,
  dispatchKnowledgeIndexed,
  dispatchShopifyOrderCreated,
  dispatchShopifyOrderUpdated,
  dispatchWooCommerceOrderCreated,
  dispatchSystemError,
} from './dispatch.js';
export type {
  DomainEventType,
  DomainEventPayload,
  MessageReceivedPayload,
  MessageSentPayload,
  MessageDeliveredPayload,
  MessageReadPayload,
  MessageFailedPayload,
  ConversationCreatedPayload,
  ConversationAssignedPayload,
  ConversationPriorityChangedPayload,
  ConversationStatusChangedPayload,
  SlaResponseDuePayload,
  SlaBreachedPayload,
  CustomerCreatedPayload,
  CustomerTaggedPayload,
  CustomerNotedPayload,
  CampaignStartedPayload,
  CampaignCompletedPayload,
  AutomationTriggeredPayload,
  FlowStartedPayload,
  FlowStepPayload,
  FlowCompletedPayload,
  AiReplyGeneratedPayload,
  AiHandoffRequestedPayload,
  AiStateChangedPayload,
  IntegrationConnectedPayload,
  IntegrationSyncedPayload,
  OrderCreatedPayload,
  OrderFulfilledPayload,
  InventoryUpdatedPayload,
  KnowledgeIndexedPayload,
  ShopifyOrderCreatedPayload,
  ShopifyOrderUpdatedPayload,
  WooCommerceOrderCreatedPayload,
  SystemErrorPayload,
} from './catalog.js';
export type { DispatchContext } from './dispatch.js';
