export const apiInfo = {
  success: true,
  name: 'FIDScript WhatsApp API',
  version: '1.0.0',
  description: 'WhatsApp API for Kenyan businesses by Next Mavens',
  documentation: 'https://whatsapp.fidscript.com/docs',
  endpoints: {
    auth: {
      'POST /api/auth/request-code': 'Request a magic sign-in code (anti-enumeration)',
      'POST /api/auth/verify-code': 'Verify code and receive JWT (admin or client)',
      'POST /api/auth/client/request-code': 'Request a registration code',
      'POST /api/auth/client/verify-code': 'Verify code, create account, receive JWT',
      'GET /api/auth/me': 'Get current admin profile',
      'GET /api/auth/client/me': 'Get current client profile',
      'GET /api/auth/client/tokens': 'Get token balance and history',
      'GET /api/stats': 'Public platform stats',
    },
    admin: {
      'GET /api/admin/instances': 'List all instances',
      'GET /api/admin/analytics': 'Platform analytics',
      'GET /api/admin/logs': 'API request logs',
    },
    clients: {
      'GET /api/clients': 'List all clients',
      'POST /api/clients': 'Create client',
      'GET /api/clients/:id': 'Get client details',
      'PATCH /api/clients/:id/toggle': 'Enable/disable client',
      'POST /api/clients/:id/reset-key': 'Reset API key',
      'DELETE /api/clients/:id': 'Delete client',
    },
    plans: {
      'GET /api/plans': 'List plans',
      'POST /api/plans': 'Create plan',
      'GET /api/plans/:id': 'Get plan details',
      'PUT /api/plans/:id': 'Update plan',
      'DELETE /api/plans/:id': 'Delete plan',
    },
    instances: {
      'POST /api/instance/create': 'Create instance',
      'GET /api/instance/credentials/:name': 'Get credentials',
      'GET /api/instance/settings/:name': 'Get settings',
      'POST /api/instance/settings/:name': 'Update settings',
      'GET /api/instance/webhook/:name': 'Get webhook config',
      'POST /api/instance/webhook/:name': 'Set webhook config',
      'GET /api/instance/connect/:name': 'Generate QR code',
      'GET /api/instance/connectionState/:name': 'Get connection state',
      'POST /api/instance/sendText/:name': 'Send text message',
      'POST /api/instance/sendMedia/:name': 'Send media message',
      'POST /api/instance/sendLocation/:name': 'Send location',
      'DELETE /api/instance/logout/:name': 'Disconnect instance',
      'DELETE /api/instance/delete/:name': 'Delete instance',
    },
    payments: {
      'GET /api/payments/packages': 'List token packages',
      'GET /api/payments/packages/:id': 'Get package details',
      'POST /api/payments/initiate': 'Initiate M-Pesa payment',
      'POST /api/payments/callback': 'Pay Hero callback URL',
      'GET /api/payments/status/:reference': 'Check payment status',
    },
  },
};
