// Thin barrel — all event types live in eventTypes.ts
export type {
  DomainEventType,
  DomainEventPayload,
  MessageReceivedPayload,
  MessageSentPayload,
  MessageDeliveredPayload,
  MessageReadPayload,
  MessageFailedPayload,
  ConversationCreatedPayload,
  ConversationAssignedPayload,
  ConversationPriorityChangedPayload,
  ConversationStatusChangedPayload,
  SlaResponseDuePayload,
  SlaBreachedPayload,
  CustomerCreatedPayload,
  CustomerTaggedPayload,
  CustomerNotedPayload,
  CampaignStartedPayload,
  CampaignCompletedPayload,
  AutomationTriggeredPayload,
  FlowStartedPayload,
  FlowStepPayload,
  FlowCompletedPayload,
  AiReplyGeneratedPayload,
  AiHandoffRequestedPayload,
  AiStateChangedPayload,
  IntegrationConnectedPayload,
  IntegrationSyncedPayload,
  OrderCreatedPayload,
  OrderFulfilledPayload,
  InventoryUpdatedPayload,
  KnowledgeIndexedPayload,
} from './eventTypes.js';
