/**
 * types.ts — re-exports all shared types from @fidscript/types.
 * Kept as a barrel so SDK consumers can `import { … } from '@fidscript/sdk/types'`
 * (the SDK's package.json routes `@fidscript/sdk/types` → `./types.ts`).
 */
export type {
  ApiResponse,
  Whoami,
  Usage,
  Instance,
  InstanceStatus,
  CreateInstance,
  SendText,
  SendMedia,
  SendLocation,
  SendContact,
  SendReaction,
  SendPoll,
  SendList,
  SendAudio,
  SendSticker,
  SendStatus,
  ContactCard,
  MessageKey,
  ListSection,
  ListRow,
  SendResult,
  Chatbot,
  ChatbotHealth,
  ChatbotAiConfig,
  LlmConnection,
  CreateLlmConnection,
  Customer,
  CustomerTimelineEvent,
  Conversation,
  ConversationMessage,
  ConversationStatus,
  ConversationPriority,
  Campaign,
  Webhook,
  MetricRollup,
  AnalyticsOverview,
  AnalyticsPeriod,
} from '@fidscript/types';
