/**
 * Generate a Postman v2.1 collection from the OpenAPI spec.
 *
 *   npm run gen:postman   (from server/)
 *
 * Reads server/openapi.json (generated by gen-openapi.ts) and emits
 * server/fidscript-postman-collection.json.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const openapi = JSON.parse(readFileSync(resolve(__dirname, '..', 'openapi.json'), 'utf-8'));

const { info, servers, paths } = openapi;
const baseUrl = (servers as Array<{ url: string }>)[0]?.url || 'https://whatsapp.fidscript.com/api/v1';

// ── per-method item builder ───────────────────────────────────────────────────

function buildItem(
  pathStr: string,
  method: string,
  op: Record<string, unknown>,
): Record<string, unknown> {
  const {
    operationId,
    summary,
    description,
    tags,
    parameters = [],
    requestBody,
    responses = {},
  } = op;

  const name = String(summary || operationId || `${method.toUpperCase()} ${pathStr}`);
  const pathParams = (parameters as Array<{ in: string; name: string }>).filter(p => p.in === 'path');

  // Build URL — replace {param} with {{param}} Postman variable
  let urlPath = pathStr;
  for (const p of pathParams) {
    urlPath = urlPath.replace(`{${p.name}}`, `{{${p.name}}}`);
  }
  const url = `${baseUrl}${urlPath}`;

  const headers = [
    ...(requestBody ? [{ key: 'Content-Type', value: 'application/json', disabled: false }] : []),
    { key: 'X-API-Key', value: '{{api_key}}', disabled: false },
  ];

  const reqBodyExample = requestBody
    ? JSON.stringify(
        (requestBody as { content?: { 'application/json'?: { example?: unknown; schema?: Record<string, unknown> } } })
          .content?.['application/json']?.example ||
          (requestBody as { content?: { 'application/json'?: { schema?: Record<string, unknown> } } })
            .content?.['application/json']?.schema || {},
        null,
        2,
      )
    : undefined;

  const item: Record<string, unknown> = {
    name,
    event: [
      {
        listen: 'test',
        script: {
          type: 'text/javascript',
          exec: [
            'if (pm.response.code >= 200 && pm.response.code < 300) {',
            '  pm.test("Successful response", function() { pm.response.to.have.status(200); });',
            '}',
          ],
        },
      },
    ],
    request: {
      method: method.toUpperCase(),
      header: headers,
      url: {
        raw: url,
        host: ['{{baseUrl}}'],
        path: urlPath.replace(/^\//, '').split('/').map(p => p.startsWith('{') ? `{{${p.slice(1, -1)}}}` : p),
      },
      description: String(description || ''),
    },
    response: Object.entries(responses).map(([code, r]) => ({
      name: `${code} response`,
      originalRequest: {
        method: method.toUpperCase(),
        header: headers,
        url: { raw: url, host: ['{{baseUrl}}'], path: urlPath.replace(/^\//, '').split('/').map(p => p.startsWith('{') ? `{{${p.slice(1, -1)}}}` : p) },
      },
      status: String(code),
      code: parseInt(code),
      body: JSON.stringify(
        (r as { content?: { 'application/json'?: { example?: unknown } } })?.content?.['application/json']?.example || { success: true },
        null,
        2,
      ),
    })),
  };

  if (reqBodyExample) {
    (item.request as Record<string, unknown>).body = {
      mode: 'raw',
      raw: reqBodyExample,
      options: { raw: { language: 'json' } },
    };
  }

  return item;
}

// ── group by tag ──────────────────────────────────────────────────────────────

const tagItems: Record<string, Record<string, unknown>[]> = {};

for (const [pathStr, methods] of Object.entries(paths)) {
  for (const [method, op] of Object.entries(methods as Record<string, unknown>)) {
    const opRecord = op as Record<string, unknown>;
    const t = (opRecord.tags as string[] | undefined)?.[0] || 'Other';
    if (!tagItems[t]) tagItems[t] = [];
    tagItems[t].push(buildItem(pathStr, method, opRecord));
  }
}

const collection = {
  info: {
    name: String(info.title || 'FIDScript WhatsApp API'),
    description: String(info.description || ''),
    schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
  },
  variable: [
    { key: 'baseUrl', value: baseUrl, type: 'string' },
    { key: 'api_key', value: 'fidscript_live_your_key_here', type: 'string' },
  ],
  auth: { type: 'apiKey', in: 'header', key: 'X-API-Key', value: '{{api_key}}', disabled: false },
  item: Object.entries(tagItems).map(([tag, items]) => ({ name: tag, item: items })),
};

const outPath = resolve(__dirname, '..', 'fidscript-postman-collection.json');
writeFileSync(outPath, JSON.stringify(collection, null, 2) + '\n');
const totalRequests = Object.values(tagItems).flat().length;
console.log(`✓ Postman collection written to ${outPath} (${totalRequests} requests, ${Object.keys(tagItems).length} folders)`);